#!/bin/sh /etc/rc.common
#
# Copyright (C) 2020-2022, IrineSistiana
#
# This file is part of mosdns.
#
# mosdns is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# mosdns is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

START=99
USE_PROCD=1

PROG=/usr/bin/mosdns
CONF=$(uci -q get mosdns.config.configfile)
CRON_FILE=/etc/crontabs/root

inital_conf() {
	config_load "mosdns"
	config_get "enabled" "config" "enabled" "0"
}

init_yaml() {
	tmpdir=$(mktemp -d) || exit 1
	log_level=$(uci -q get mosdns.config.log_level)
	log_file=$(uci -q get mosdns.config.logfile)
	listen_port=$(uci -q get mosdns.config.listen_port)
	cache_size=$(uci -q get mosdns.config.cache_size)
	cache_survival_time=$(uci -q get mosdns.config.cache_survival_time)
	minimal_ttl_custom=$(uci -q get mosdns.config.minimal_ttl)
	maximum_ttl_custom=$(uci -q get mosdns.config.maximum_ttl)
	local_dns=$(/usr/share/mosdns/mosdns.sh dns | xargs -n1 echo "        - addr:")
	remote_dns1=$(uci -q get mosdns.config.remote_dns1)
	remote_dns2=$(uci -q get mosdns.config.remote_dns2)
	adblock=$(/usr/share/mosdns/mosdns.sh ad)
	enable_pipeline=$(uci -q get mosdns.config.enable_pipeline)
	[ $enable_pipeline = 0 ] && enable_pipeline=false
	[ $enable_pipeline = 1 ] && enable_pipeline=true
	sed "s,log_level,$log_level,g;s,log_file,$log_file,g; \
	s,listen_port,$listen_port,g;s,cache_size,$cache_size,g; \
	s,cache_survival_time,$cache_survival_time,g; \
	s,minimal_ttl_custom,$minimal_ttl_custom,g; \
	s,maximum_ttl_custom,$maximum_ttl_custom,g; \
	s,remote_dns1,$remote_dns1,g;s,remote_dns2,$remote_dns2,g; \
	s,adblock,$adblock,g;s,remote_dns_pipeline,$enable_pipeline,g" \
	/usr/share/mosdns/default.yaml > $(uci -q get mosdns.config.configfile)
	echo "${local_dns}" > $tmpdir/local_dns.txt
	sed -i -e '/- addr: local_dns/{r '$tmpdir/local_dns.txt -e';d}' \
	$(uci -q get mosdns.config.configfile)
	rm -rf $tmpdir
}

service_triggers() {
	procd_add_reload_trigger "mosdns"
}

restore_setting() {
	sed -i "/list server/d" /etc/config/dhcp
	uci set dhcp.@dnsmasq[0].noresolv='0'
	uci del dhcp.@dnsmasq[0].cachesize
	uci commit dhcp
}

redirect_setting() {
	if [ "${CONF}" = "/etc/mosdns/config.yaml" ]; then
		sed -i "/list server/d" /etc/config/dhcp
		uci add_list dhcp.@dnsmasq[0].server="127.0.0.1#$(uci -q get mosdns.config.listen_port)"
		uci set dhcp.@dnsmasq[0].rebind_protection='0'
		uci set dhcp.@dnsmasq[0].noresolv="1"
		uci set dhcp.@dnsmasq[0].cachesize='0'
		uci commit dhcp
	else
		sed -i "/list server/d" /etc/config/dhcp
		uci add_list dhcp.@dnsmasq[0].server="127.0.0.1#$(cat /etc/mosdns/config_custom.yaml | awk -F'[:" ]+' '/^\s+addr:/{for(i=1;i<=NF;i++){if($i~/^[0-9]+$/){print $i;exit}}}')"
		uci set dhcp.@dnsmasq[0].rebind_protection='0'
		uci set dhcp.@dnsmasq[0].noresolv="1"
		uci set dhcp.@dnsmasq[0].cachesize='0'
		uci commit dhcp
	fi
}

reload_others() {
	/etc/init.d/network reload
	/etc/init.d/dnsmasq reload
}

reload_service() {
	stop
	sleep 1
	start
}

setcron() {
	sed -i '/mosdns.sh/d' $CRON_FILE 2>/dev/null
	[ "$(uci -q get mosdns.config.geo_auto_update)" -eq 1 ] && echo "0 $(uci -q get mosdns.config.geo_update_day_time) * * $(uci -q get mosdns.config.geo_update_week_time) /usr/share/mosdns/mosdns.sh geodata" >>$CRON_FILE
	crontab $CRON_FILE
}

delcron() {
	sed -i '/mosdns.sh/d' $CRON_FILE 2>/dev/null
	crontab $CRON_FILE
}

start_service() {
	inital_conf
	[ $enabled != 1 ] && return 1
	delcron
	setcron
	[ "${CONF}" = "/etc/mosdns/config.yaml" ] && init_yaml
	cat /dev/null > $(/usr/share/mosdns/mosdns.sh logfile)
	[ ! "$(uci -q get mosdns.config.ad_source)" = "geosite.dat" ] && cat /dev/null > /etc/mosdns/rule/adlist.txt
	procd_open_instance mosdns
	procd_set_param command $PROG start -c "$CONF"
	procd_set_param user root
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
	procd_close_instance mosdns

	restore_setting
	[ "$(uci -q get mosdns.config.redirect)" -eq 1 ] && redirect_setting
	reload_others

	[ ! "$(uci -q get mosdns.config.ad_source)" = "geosite.dat" ] && /usr/share/mosdns/mosdns.sh adlist_update &> /dev/null &
}

stop_service() {
	pgrep -f /usr/bin/mosdns | xargs kill -9 >/dev/null 2>&1
	config_load "mosdns"
	[ "$(uci -q get mosdns.config.enabled)" = "0" ] && restore_setting
	reload_others
	delcron
}
