name: Build Packages

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.tag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - aarch64_cortex-a72
          - aarch64_cortex-a76
          - aarch64_generic
          - arm_arm1176jzf-s_vfp
          - arm_arm926ej-s
          - arm_cortex-a15_neon-vfpv4
          - arm_cortex-a5_vfpv4
          - arm_cortex-a7
          - arm_cortex-a7_neon-vfpv4
          - arm_cortex-a7_vfpv4
          - arm_cortex-a8_vfpv3
          - arm_cortex-a9
          - arm_cortex-a9_neon
          - arm_cortex-a9_vfpv3-d16
          - arm_fa526
          - arm_xscale
          - i386_pentium-mmx
          - i386_pentium4
          - loongarch64_generic
          - mips64_mips64r2
          - mips64_octeonplus
          - mips64el_mips64r2
          - mips_24kc
          - mips_4kec
          - mips_mips32
          - mipsel_24kc
          - mipsel_24kc_24kf
          - mipsel_74kc
          - mipsel_mips32
          - riscv64_riscv64
          - x86_64
        tag:
          - openwrt-24.10
          - openwrt-25.12

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build preparation
        run: |
          sed -i '/golang-package/a \\tGO_PKG_DEFAULT_LDFLAGS:=-w -s -extldflags "-static"' mosdns/Makefile
          sed -i '/golang-package/a \\tGO_PKG_DEFAULT_LDFLAGS:=-w -s -extldflags "-static"' geo2txt/Makefile
          git clone https://github.com/sbwml/v2ray-geodata
          echo "SKIP_BUILD=0" >> $GITHUB_ENV
          if [ "${{ matrix.tag }}" = "openwrt-25.12" ] && [ "${{ matrix.arch }}" = "riscv64_riscv64" ]; then
            echo "EFFECTIVE_ARCH=riscv64_generic" >> $GITHUB_ENV
            echo "ARCH=riscv64_generic-${{ matrix.tag }}" >> $GITHUB_ENV
          elif [ "${{ matrix.tag }}" = "openwrt-25.12" ] && [ "${{ matrix.arch }}" = "mips_4kec" ]; then
            echo "SKIP_BUILD=1" >> $GITHUB_ENV
          else
            echo "EFFECTIVE_ARCH=${{ matrix.arch }}" >> $GITHUB_ENV
            echo "ARCH=${{ matrix.arch }}-${{ matrix.tag }}" >> $GITHUB_ENV
          fi

      - name: Build Packages
        if: ${{ env.SKIP_BUILD == '0' }}
        uses: sbwml/openwrt-gh-action-sdk@go1.27
        env:
          FEEDNAME: packages_ci
          PACKAGES: luci-app-mosdns
          NO_REFRESH_CHECK: true

      - name: Create compress files
        if: ${{ env.SKIP_BUILD == '0' }}
        continue-on-error: true
        run: |
          tar -zcvf ${{ env.ARCH }}.tar.gz -C bin/packages/${{ env.EFFECTIVE_ARCH }}/ packages_ci

      - name: Upload packages
        if: ${{ env.SKIP_BUILD == '0' }}
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          prerelease: false
          artifacts: "${{ env.ARCH }}.tar.gz"
